version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    ports:
      - "3306:3306"
    networks:
      static_network:
        ipv4_address: 172.18.0.2

networks:
  static_network:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
